web:
  build: ./app
  command: python -u app.py
  ports:
    - "8080:5000"
  volumes:
    - ./app:/app
  links:
    - mongodb
    - neo4j

mongodb:
  image: mongo:3.6.1

mongo-seed:
  image: mongo:3.6.1
  restart: "no"
  links: 
    - mongodb
  volumes:
    - ./app:/app
  command:
    "mongoimport --host mongodb --port 27017 --db appdb --collection restaurant --drop --mode upsert --type json --file /app/data/restaurants.json --jsonArray"
  
  command:
    "mongoimport --host mongodb --port 27017 --db appdb --collection piste_cyclable --drop --mode upsert --type json --file /app/data/pistes_cyclables.json --jsonArray"
neo4j:
  image: neo4j:latest