version: "3"
services:
  app:
    build: ./app
    ports:
      - 8080:5000
    environment:
      - production=1
    links:
      - mongo
      - neo4j

  mongo:
    image: mongo:4.2
    volumes: 
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  neo4j:
    image: neo4j
    volumes: 
      - ./data/neo:/data/databases/graph.db
    environment:
      - NEO4J_AUTH=neo4j/projetBD
    ports:
      - 7474:7474
      - 7687:7687